### ISSUE TITLE
Project needs a readme.md

### ISSUE THREAD

**Issue by salikadave** [Pragalbha-Patil/React-Native-TechStack#1]
Please add a readme for this project showing how to run it for development, I'd like to contribute to this project!

**Comment by Pragalbha-Patil** [comment]
Thank you @salikadave , I have added a Readme, hope you have a great time contributing to my project. Developers like you makes GitHub a great place.

**Comment by salikadave** [comment]
Glad to help ! Also please add what kind of components you are preparing.
